### ISSUE TITLE
Cannot execute

### ISSUE THREAD

**Issue by Laamis** [Neph0/steamMarketWatcher#2]
When trying to execute the file, it just shuts down. After trying to execute the file inside IDLE, it says that print is missing parantheses. Adding the parantheses just skips it to the next error etc. 
Is something wrong in my end?

**Comment by Neph0** [comment]
Hello, sorry for the one-year late answer. You're most likely running it with Python 3. The script was designed for Python 2. You can download it [here](https://www.python.org/download/releases/2.7/).
